### ISSUE TITLE
[Enhancement] GM Side Exclusions

### ISSUE THREAD

**Issue by Ruidolph** [reyzor1991/pf2e-summons-helper#1]
I'm running a game and I'd like to ability to exclude certain monsters from the list of summonable creatures. 

EX: One of adventure paths has named creatures and the named creatures are showing up as options.

**Comment by Ruidolph** [comment]
I see you marked this as completed but there's no settings for this module or anything, how do I do it?

**Comment by reyzor1991** [comment]
Now only common monsters show as should be

specific monster always rare unique or uncommon

**Comment by Ruidolph** [comment]
Thank you! Appreciate the quick work and response!
