### ISSUE TITLE
GM Settings to filter creatures

### ISSUE THREAD

**Issue by anfelder** [reyzor1991/pf2e-summons-helper#2]
Add some settings to allow the GM to filter out creatures from what is shown to the players to be selected. For example filtering by source to exclude PFS, APs, etc. Also a setting to only show either the Bestiary or Monster Core version of a creature if both exist. 

In the screenshot, the Deadtide skeleton guard is an Abomination Vaults creature, the exploding skeleton guard is from PFS, and the top creature is a named creature from an AP.

![image](https://github.com/user-attachments/assets/7af3b23c-6618-4569-b851-14c29d376dea)
![image](https://github.com/user-attachments/assets/d494ceca-4580-4122-a205-4bb293bee112)
![image](https://github.com/user-attachments/assets/0afb6717-ce50-4ae6-9106-823d514c5b04)

**Comment by reyzor1991** [comment]
Only partitial implementation, duplicates can't delete for now, maybe in future find good solution for it
